export const T = {
  en: {
    nav: ["Work", "About", "Contact"],
    hero: { greeting: "Hello, I'm", name: "Umidbek Karimov", role: "3D Animator | Motion Designer", bio: "Character-driven 3D Animator & Motion Designer specializing in fluid, performance-based animations and dynamic video content. My workflow is strictly rooted in the fundamentals of motion—weight, timing, and storytelling—harnessed within Autodesk Maya and Adobe After Effects to deliver high-quality visual solutions. Open to full-time and freelance opportunities in game studios, animation productions, and creative agencies.", cta1: "View Showreel", cta2: "Contact Me", badge: "Available for hire", scroll: "Scroll" },
    work: { label: "My Portfolio", heading: "Giving Life to\n3D Characters", showreelTitle: "Production Showreel 2026", showreelMeta: "2 min 30 sec  ·  HD 1080p", projects: [
      { title: "Squirrel Animation", category: "Character Animation · Blender", video: "/videos/squirrel-animation.mp4", poster: "/squirrel-thumbnail.png" },
      { title: "Walk Cycle Practice", category: "Body Mechanics · Maya", video: "/videos/walk-cycle-animation.mp4", poster: "/walk-cycle-thumbnail.png" },
      { title: "Squash & Stretch", category: "Animation Fundamentals · Maya", video: "/videos/squash-stretch-animation.mp4", poster: "/squash-stretch-thumbnail.png" },
      { title: "Shadow in the Old City", category: "CGI & Lighting · Maya", video: "/videos/shadow-city-animation.mp4", poster: "/shadow-city-thumbnail.png" }
    ] },
    about: { label: "About Me", heading: "Timing. Weight.\nCharacter", bio1: "I've been studying and practicing 3D animation extensively, driven by a deep passion for character performance and believable movement. My workflow combines Autodesk Maya and Blender, applying core principles like timing, spacing, weight, and acting.", bio2: "I continuously study animation to improve both technical execution and storytelling through motion, refinement and push the limits of what motion can express.", software: "Software", skills: "Specialisations", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Approach", labelProj: "Main Tool", labelStyle: "Focus", openToWork: "Open to Work", openToWorkDesc: "Currently looking for 3D Animation roles or freelance opportunities to bring characters to life." },
    contact: { label: "Contact", heading: "Let's Create\nSomething Great", sub: "Open to freelance, full-time roles, and creative collaborations.", resume: "Download Résumé", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Send Email", formTitle: "Quick Message", namePh: "Your Name", emailPh: "Your Email", msgPh: "Your Message", send: "Send Message", sending: "Sending…", sent: "Message Sent ✓" },
    footer: "Crafted with obsession. All rights reserved.",
  },
  ru: {
    nav: ["Работы", "Обо мне", "Контакты"],
    hero: { greeting: "Привет, я", name: "Умидбек Каримов", role: "3D Animator | Motion Designer", bio: "3D-аниматор и Motion Designer. Специализируюсь на создании плавной, выразительной анимации персонажей и динамичного видеоконтента. В работе строго опираюсь на фундаментальные принципы движения — механику тела, вес, тайминг и сторителлинг в среде Autodesk Maya и After Effects для создания качественных визуальных решений. Открыт к долгосрочному сотрудничеству (full-time) и проектной работе (freelance) с игровыми студиями, анимационными производствах и видеоагентствами.", cta1: "Смотреть Showreel", cta2: "Написать", badge: "Открыт к работе", scroll: "Вниз" },
    work: { label: "Моё портфолио", heading: "Оживляя\n3D-персонажей", showreelTitle: "Шоурил 2026", showreelMeta: "2 мин 30 сек  ·  HD 1080p", projects: [
      { title: "Анимация белки (Squirrel Animation)", category: "Анимация персонажей · Blender", video: "/videos/squirrel-animation.mp4", poster: "/squirrel-thumbnail.png" },
      { title: "Практика походки (Walk Cycle)", category: "Механика тела · Maya", video: "/videos/walk-cycle-animation.mp4", poster: "/walk-cycle-thumbnail.png" },
      { title: "Сквош и стретч (Bouncing Ball)", category: "Основы анимации · Maya", video: "/videos/squash-stretch-animation.mp4", poster: "/squash-stretch-thumbnail.png" },
      { title: "Тень в старом городе (Shadow City)", category: "CGI и освещение · Maya", video: "/videos/shadow-city-animation.mp4", poster: "/shadow-city-thumbnail.png" }
    ] },
    about: { label: "Обо мне", heading: "Тайминг. Вес.\nПерсонаж.", bio1: "Я активно изучаю и практикую 3D-анимацию, движимый глубокой страстью к актерской игре персонажей и реалистичности их движений. В работе сочетаю Autodesk Maya и Blender.", bio2: "Я применяю ключевые принципы — тайминг, спейсинг, вес и актерское мастерство, чтобы постоянно совершенствовать визуальное повествование через движение.", software: "Инструменты", skills: "Специализации", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Подход", labelProj: "Инструмент", labelStyle: "Фокус", openToWork: "Открыт к работе", openToWorkDesc: "Ищу позиции 3D Animator или фриланс-проекты для оживления персонажей." },
    contact: { label: "Контакты", heading: "Создадим\nЧто-то Великое", sub: "Открыт для фриланса, постоянной работы и коллабораций.", resume: "Скачать Резюме", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Написать Email", formTitle: "Быстрое сообщение", namePh: "Ваше имя", emailPh: "Ваш Email", msgPh: "Ваше сообщение", send: "Отправить", sending: "Отправляется…", sent: "Отправлено ✓" },
    footer: "Создано с одержимостью. Все права защищены.",
  },
  uz: {
    nav: ["Ishlar", "Men haqimda", "Aloqa"],
    hero: { greeting: "Salom, men", name: "Umidbek Karimov", role: "3D Animator | Motion Designer", bio: "3D Animator va Motion Designer. Qahramonlar animatsiyasi hamda dinamik video kontentlar yaratishga ixtisoslashganman. Ish jarayonimda animatsiyaning fundamental prinsiplari — tana mexanikasi, ogʻirlik, tayming va vizual hikoyachilik qonuniyatlariga qatʼiy eʼtibor qaratgan holda, Autodesk Maya va After Effects muhitida yuqori sifatli vizual yechimlar ishlab chiqaman. Geymdev studiyalari, animatsiya ishlab chiqarish jamoalari va video agentliklarda shtatdagi (full-time) hamda frilans loyihalarda ishlashga tayyorman.", cta1: "Showreelni ko'rish", cta2: "Bog'lanish", badge: "Ishga tayyor", scroll: "Pastga" },
    work: { label: "Mening ishlarim", heading: "3D qahramonlarni\njonlantirish", showreelTitle: "Showreel 2026", showreelMeta: "2 daqiqa 30 soniya  ·  HD 1080p", projects: [
      { title: "Tiyin animatsiyasi (Squirrel Animation)", category: "Qahramonlar animatsiyasi · Blender", video: "/videos/squirrel-animation.mp4", poster: "/squirrel-thumbnail.png" },
      { title: "Qadam tashlash harakati (Walk Cycle)", category: "Tana mexanikasi · Maya", video: "/videos/walk-cycle-animation.mp4", poster: "/walk-cycle-thumbnail.png" },
      { title: "Bouncing Ball (Squash & Stretch)", category: "Animatsiya asoslari · Maya", video: "/videos/squash-stretch-animation.mp4", poster: "/squash-stretch-thumbnail.png" },
      { title: "Eski shahardagi soya (Shadow City)", category: "CGI va yoritish · Maya", video: "/videos/shadow-city-animation.mp4", poster: "/shadow-city-thumbnail.png" }
    ] },
    about: { label: "Men haqimda", heading: "Vaqt, Og'irlik,\nXarakter", bio1: "Men qahramonlar ijrosi va ishonchli harakatlar dinamikasiga bo'lgan cheksiz ishtiyoqim sababli 3D animatsiyani chuqur o'rganib va amalda qo'llab kelmoqdaman. Autodesk Maya va Blender dasturlaridan foydalanaman.", bio2: "Vaqt (timing), masofa (spacing), og'irlik (weight) va aktyorlik mahorati kabi fundamental prinsiplardan foydalanib, harakat orqali hikoyalarni ifodalash chegaralarini kengaytiraman.", software: "Dasturlar", skills: "Ixtisosliklar", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Yondashuv", labelProj: "Asosiy vosita", labelStyle: "Yo'nalish", openToWork: "Ishga tayyor", openToWorkDesc: "3D Animation yoki freelance imkoniyatlar uchun ochiqman - qahramonlarga hayot bag'ishlash." },
    contact: { label: "Aloqa", heading: "Ajoyib Narsa\nBirga Yarataylik", sub: "Frilanс, to'liq kunlik ish va ijodiy hamkorlik uchun ochiqman.", resume: "Rezyume yuklab olish", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Email yuborish", formTitle: "Tezkor xabar", namePh: "Ismingiz", emailPh: "Emailingiz", msgPh: "Xabaringiz", send: "Yuborish", sending: "Yuborilmoqda…", sent: "Yuborildi ✓" },
    footer: "Ehtiros bilan yaratilgan. Barcha huquqlar himoyalangan.",
  },
};
