export const T = {
  en: {
    nav: ["Work", "About", "Contact"],
    hero: { greeting: "Hello, I'm", name: "Umidbek Karimov", role: "Junior 3D Animator | Motion Designer", bio: "Character-driven 3D Animator & Motion Designer specializing in fluid, performance-based animations and dynamic video content. My workflow is strictly rooted in the fundamentals of motion—weight, timing, and storytelling—harnessed within Autodesk Maya and Adobe After Effects to deliver high-quality visual solutions. Open to full-time and freelance opportunities in game studios, animation productions, and creative agencies.", cta1: "View Showreel", cta2: "Contact Me", badge: "Available for hire", scroll: "Scroll" },
    work: { label: "My Portfolio", heading: "Giving Life to\n3D Characters", showreelTitle: "Production Showreel 2026", showreelMeta: "2 min 30 sec  ·  HD 1080p", projects: [{ title: "Post - Production & Commercial Motion", category: "Motion Capture · Post-Production" }, { title: "Soon..", category: "3D · CGI" }] },
    about: { label: "About Me", heading: "Timing. Weight.\nCharacter", bio1: "I'm a Junior 3D Animator dedicated to mastering character motion. I focus on creating believable movement using Autodesk Maya.", bio2: "I enjoy the process of bringing characters to life through physics-based animation.", software: "Software", skills: "Specialisations", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Approach", labelProj: "Main Tool", labelStyle: "Focus", openToWork: "Open to Work", openToWorkDesc: "Currently looking for Junior 3D Animation roles or freelance opportunities to bring characters to life." },
    contact: { label: "Contact", heading: "Let's Create\nSomething Great", sub: "Open to freelance, full-time roles, and creative collaborations.", resume: "Download Résumé", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Send Email", formTitle: "Quick Message", namePh: "Your Name", emailPh: "Your Email", msgPh: "Your Message", send: "Send Message", sending: "Sending…", sent: "Message Sent ✓" },
    footer: "Crafted with obsession. All rights reserved.",
  },
  ru: {
    nav: ["Работы", "Обо мне", "Контакты"],
    hero: { greeting: "Привет, я", name: "Умидбек Каримов", role: "Junior 3D Animator | Motion Designer", bio: "3D-аниматор и Motion Designer. Специализируюсь на создании плавной, выразительной анимации персонажей и динамичного видеоконтента. В работе строго опираюсь на фундаментальные принципы движения — механику тела, вес, тайминг и сторителлинг в среде Autodesk Maya и After Effects для создания качественных визуальных решений. Открыт к долгосрочному сотрудничеству (full-time) и проектной работе (freelance) с игровыми студиями, анимационными производствах и видеоагентствами.", cta1: "Смотреть Showreel", cta2: "Написать", badge: "Открыт к работе", scroll: "Вниз" },
    work: { label: "Моё портфолио", heading: "Оживляя\nцифровых персонажей", showreelTitle: "Production Showreel 2026", showreelMeta: "2 мин 30 сек  ·  HD 1080p", projects: [{ title: "Post - Production & Commercial Motion", category: "Motion Capture · Post-Production" }, { title: "Soon..", category: "3D · CGI" }] },
    about: { label: "Обо мне", heading: "Тайминг. Вес.\nПерсонаж.", bio1: "Я Junior 3D-аниматор, посвятивший себя изучению движения персонажей. Я фокусируюсь на создании правдоподобных движений в Autodesk Maya.", bio2: "Мне нравится процесс оживления персонажей через физически корректную анимацию.", software: "Инструменты", skills: "Специализации", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Подход", labelProj: "Инструмент", labelStyle: "Фокус", openToWork: "Открыт к работе", openToWorkDesc: "Ищу позиции Junior 3D Animator или фриланс-проекты для оживления персонажей." },
    contact: { label: "Контакты", heading: "Создадим\nЧто-то Великое", sub: "Открыт для фриланса, постоянной работы и коллабораций.", resume: "Скачать Резюме", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Написать Email", formTitle: "Быстрое сообщение", namePh: "Ваше имя", emailPh: "Ваш Email", msgPh: "Ваше сообщение", send: "Отправить", sending: "Отправляется…", sent: "Отправлено ✓" },
    footer: "Создано с одержимостью. Все права защищены.",
  },
  uz: {
    nav: ["Ishlar", "Men haqimda", "Aloqa"],
    hero: { greeting: "Salom, men", name: "Umidbek Karimov", role: "Junior 3D Animator | Motion Designer", bio: "3D Animator va Motion Designer. Qahramonlar animatsiyasi hamda dinamik video kontentlar yaratishga ixtisoslashganman. Ish jarayonimda animatsiyaning fundamental prinsiplari — tana mexanikasi, ogʻirlik, tayming va vizual hikoyachilik qonuniyatlariga qatʼiy eʼtibor qaratgan holda, Autodesk Maya va After Effects muhitida yuqori sifatli vizual yechimlar ishlab chiqaman. Geymdev studiyalari, animatsiya ishlab chiqarish jamoalari va video agentliklarda shtatdagi (full-time) hamda frilans loyihalarda ishlashga tayyorman.", cta1: "Showreelni ko'rish", cta2: "Bog'lanish", badge: "Ishga tayyor", scroll: "Pastga" },
    work: { label: "Mening ishlarim", heading: "3D qahramonlarni\njonlantirish", showreelTitle: "Production Showreel 2026", showreelMeta: "2 daqiqa 30 soniya  ·  HD 1080p", projects: [{ title: "Post - Production & Commercial Motion", category: "Motion Capture · Post-Production" }, { title: "Soon..", category: "3D · CGI" }] },
    about: { label: "Men haqimda", heading: "Vaqt, Og'irlik,\nXarakter", bio1: "Men belgi harakatini o'rganishga bag'ishlangan Junior 3D animatorman. Autodesk Maya yordamida ishonchli harakatlar yaratishga e'tibor qarataman.", bio2: "Fizikaga asoslangan animatsiya orqali qahramonlarga hayot bag'ishlash jarayonidan zavqlanaman.", software: "Dasturlar", skills: "Ixtisosliklar", softwareList: ["Autodesk Maya", "Blender", "After Effects"], skillsList: ["Character Animation", "Motion Editing", "Motion Design"], statsExp: "Learning Mindset", statsProj: "Autodesk Maya", statsStyle: "Character Animation", labelExp: "Yondashuv", labelProj: "Asosiy vosita", labelStyle: "Yo'nalish", openToWork: "Ishga tayyor", openToWorkDesc: "Junior 3D Animation yoki freelance imkoniyatlar uchun ochiqman — qahramonlarga hayot bag'ishlash." },
    contact: { label: "Aloqa", heading: "Ajoyib Narsa\nBirga Yarataylik", sub: "Frilanс, to'liq kunlik ish va ijodiy hamkorlik uchun ochiqman.", resume: "Rezyume yuklab olish", telegram: "Telegram", linkedin: "LinkedIn", instagram: "Instagram", gmail: "Email yuborish", formTitle: "Tezkor xabar", namePh: "Ismingiz", emailPh: "Emailingiz", msgPh: "Xabaringiz", send: "Yuborish", sending: "Yuborilmoqda…", sent: "Yuborildi ✓" },
    footer: "Ehtiros bilan yaratilgan. Barcha huquqlar himoyalangan.",
  },
};
